server:
  port: 8766


spring:
  application:
    name: authservice

  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:

  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

info:
  app:
    name: Auth Service
    version: 1.0.0
    description: Production Ready Auth Service

eureka:

  instance:

    prefer-ip-address: true


  client:

    service-url:
      defaultZone:
        http://localhost:8761/eureka/